adding feedback from Alejandro to clarify instructions
Pyrrha-Platform/Pyrrha-Rules-Decision pull request #48
Opened 2021-07-27 23:29 UTC by upkarlidder

Signed-off-by: Upkar Lidder <ulidder@us.ibm.com>

@Aquijada52 pls review again. Thank you for your feedback! 🙏🏽 

------
**Describe at a high level the solution you're providing**
A clear and concise description of what you changed.

**Is this a patch, a minor version change, or a major version change**
Patch, minor, or major.

**Is this related to an open issue?**
Please provide the link.

**Additional context**
Add any other technical detail or considerations here.

2021-08-04 14:11 UTC, krook commented
Looks like there are conflicts to resolve. I can't quite eyeball which is more recent @upkarlidder. Can you please take a pass?

2021-08-30 19:24 UTC, krook requested changes
I took another pass at merging the conflicts but I gave up since I didn't know which were more up to date. Are you able to review and merge?

2021-08-31 01:41 UTC, upkarlidder commented
I will check and merge. Thanks @krook.

2022-04-05 20:37 UTC, krook commented
This still relevant @upkarlidder?

2025-03-24 12:28 UTC, krook submitted a review, later dismissed

2025-03-24 12:43 UTC, krook approved these changes

2025-03-24 12:43 UTC, merged